[package]
name = "signals"
version = "0.1.0"
authors = ["Al McElrath <hello@yrns.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-signals = "0.3.16"
pin-project = "1.0.2"
futures-lite = "1.11.3"
